### PR TITLE
Add new tests some changes in XSl

### PR DESCRIPTION
**Pull request by usama49**
new tests for contracted and un contracted, bold italic, underline , strike etc
Some changes in XSL to treat bold. italic properly.

### CODE REVIEW

**Comment by josteinaj** [comment]
Looks good to me.

**Comment by bertfrees** [comment]
OK great. Good test coverage.

Implementing emphasis in XSLT instead of liblouis should be OK I think considering the basic requirements that Norwegian braille has for emphasis, and considering the fact that you want the ordering of tags to be preserved (https://github.com/snaekobbi/liblouis/issues/10) which is currently not possible with liblouis.

I'm not so sure the implementation is that great, there's a lot of code duplication. The treewalk mode is more something internal and should probably not be overridden. Could this maybe be solved with an extra indirection? treewalk calls another mode for just the text content?

The alternative I guess is to handle emphasis in the Java code.

**Comment by bertfrees** [comment]
By the way the reason why em, strong, etc. were ignored is probably because I did something wrong in the Java code. Even though we handle emphasis in XSLT now, I want to fix that. There is still some code left in both block-translate.xsl and no-no-g0.utb for handling emphasis in liblouis. That should be removed if we want to avoid it is handled twice.

**Comment by josteinaj** [comment]
> there's a lot of code duplication

Yeah, I know, it would be good to have a cleaner way of doing it. We might be able to solve it with some extra modes. I don't think a text content mode would be sufficient for strong/em, as they might be nested, but a text mode would be useful for looking for e-mail addresses etc. probably.

Maybe if we could use a mode called for instance "custom", where we could do something like this?:

``` xml
<xsl:template match="em | i" mode="custom">
    <xsl:copy>
        <!-- do stuff -->
        <xsl:apply-templates select="." mode="treewalk"/>
        <!-- do other stuff -->
    </xsl:copy>
</xsl:template>
```

I dunno...

> Even though we handle emphasis in XSLT now, I want to fix that

It would be good if liblouis could be used for em/strong, so that the liblouis table could be used to declare the characters to use. We could instruct liblouis to render strong as em using the transform variable in the XSLT. I guess the only downside is that we wouldn't get the proper ordering when the strong or em tags occur at the same position? Could there be any way of forcing the proper ordering in the XSLT? Maybe using a two-pass process to fix the output or something?

**Comment by bertfrees** [comment]
> I guess the only downside is that we wouldn't get the proper ordering when the strong or em tags occur at the same position? Could there be any way of forcing the proper ordering in the XSLT?

Yes it should be possible with some workarounds. Doing it in the XSLT definitely seems cleaner though.

**Comment by josteinaj** [comment]
Ok, so you suggest we essentially keep it as we have it now?

**Comment by bertfrees** [comment]
I guess I don't see that much advantage in handling it in Liblouis anymore, especially since you already have implemented it in XSLT now. I thought you already made the decision and were not considering doing it Liblouis anymore.

The only advantage I can see for having it in Liblouis is to get the same behavior in other software that uses liblouis (screen readers etc.). So maybe we can keep the definitions in the Liblouis table but remove the `text-transform` properties from the XSLT? Or maybe even have an option to choose between the two paths (XSLT path if order is important, Liblouis path otherwise)?

**Comment by josteinaj** [comment]
Yes, I think it's good to keep the definitions in the table for use by screen readers. If we just remove the `louis-ital`, `louis-bold` etc. part of the XSLT then I assume we don't have to worry about the definitions in the table?

**Comment by bertfrees** [comment]
Correct.

**Comment by bertfrees** [comment]
See https://github.com/snaekobbi/pipeline-mod-nlb/issues/20

**Pull request merged**
