### PR TITLE
v1.6

### PR DESCRIPTION
**Pull request by josteinaj**
- changed CSS to SCSS, and made several updates
- allow all languages, easier to override css, move pre-processing
  - stylesheet option (single file widget)
  - don't fail if document language is not "no"
  - moved pre-processing out of transformer
  - added/reorganized some tests as well

### CODE REVIEW

**Comment by bertfrees** [comment]
I had already seen the changes, looks good to me. You may merge things yourself if you think they're ready.

**Comment by josteinaj** [comment]
Ok, I will. Should I try and release them to sonatype as well?

**Comment by bertfrees** [comment]
If you want to do that you definitely may. Release procedure is in the README I believe.

**Comment by josteinaj** [comment]
Great, I'll try.

**Pull request merged**
